// Locked-in counterfactual (contrast) class per study sample.
//
// The cues condition shows exactly one contrast class out of the several the
// RExNet report carries. That pick used to come from getDeterministicFoil():
// stable for a given sample id, but arbitrary, and it silently moves when a
// bundle's contrast list changes (the same clip picks a different foil in
// data_v6 than in data_v1 whenever the predicted class differs). This table
// pins the choice for every sample listed in a bundle's split CSVs
// (training / testing / post-test and their *-formative variants), so the
// study shows the same counterfactual on every run and every rebuild.
//
// Keys: bundle root -> sample id -> contrast class. A value must name one of
// that sample's contrast classes (matched case-insensitively); an unknown or
// missing entry falls back to the deterministic hash, so a partial table is
// safe. Hand-edit a value to re-aim one sample at a different counterfactual.
//
// Generated by dev/gen_foil_overrides.mjs, which preserves existing values —
// regenerating after a bundle refresh only adds the samples that are new.

export const FOIL_OVERRIDES: Record<string, Record<string, string>> = {
  'data_v1': {
    // ── lung ──
    'fraiwan_218': 'Stridor', // testing
    'fraiwan_53': 'Normal', // testing
    'hflung_steth_20180816_11_06_45_6': 'Wheeze', // testing
    'hflung_steth_20181022_09_55_05_4': 'Crackle', // testing
    'hflung_steth_20190807_10_44_45_2': 'Rhonchi', // testing
    'hflung_steth_20190808_10_02_09_8': 'Rhonchi', // testing
    'hflung_trunc_2019-05-16-14-23-13-L5_8_14': 'Crackle', // testing
    'hflung_trunc_2019-05-28-14-07-13-L5_5_12': 'Rhonchi', // testing
    'hflung_trunc_2019-07-16-10-11-12-L1_13_10': 'Crackle', // testing
    'hflung_trunc_2019-07-16-10-41-27-L4_10_13': 'Rhonchi', // testing
    'hflung_trunc_2019-07-17-10-38-33-L2_5_0': 'Rhonchi', // testing
    'hflung_trunc_2019-08-08-09-36-47-L6_0_14': 'Crackle', // testing
    'hflung_trunc_2019-08-08-11-08-00-L4_10_9': 'Crackle', // testing
    'icbhi_156_8b3_Pl_mc_AKGC417L_5': 'Normal', // testing
    'icbhi_166_1p1_Ll_sc_Meditron_24': 'Stridor', // testing
    'sprsound_40985693_3.4_0_p2_8627_2': 'Stridor', // testing
    'sprsound_41132911_3.0_0_p2_6066_1': 'Crackle', // testing
    'sprsound_41255551_4.5_0_p2_11683_2': 'Crackle', // testing
    'sprsound_41263355_3.4_0_p4_972_1': 'Rhonchi', // testing
    'sprsound_64743918_7.0_0_p1_2518_0': 'Stridor', // testing
    'fraiwan_140': 'Rhonchi', // training
    'hflung_trunc_2019-05-28-14-44-45-L5_5_12': 'Crackle', // training
    'hflung_trunc_2019-07-16-11-46-52-L5_11_18': 'Stridor', // training
    'hflung_trunc_2019-07-17-11-06-06-L2_9_15': 'Crackle', // training
    'icbhi_116_1b2_Pl_sc_Meditron_3': 'Rhonchi', // training
    // ── bird ──
    'bird_Recording_1_Recording_1_Segment_06_299': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_09_93': 'Ovenbird', // testing
    'bird_Recording_1_Recording_1_Segment_10_89': 'Eastern Towhee', // testing
    'bird_Recording_1_Recording_1_Segment_11_150': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_15_40': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_22_16': 'Ovenbird', // testing
    'bird_Recording_1_Recording_1_Segment_22_204': 'Eastern Towhee', // testing
    'bird_Recording_1_Recording_1_Segment_29_164': 'Eastern Towhee', // testing
    'bird_Recording_1_Recording_1_Segment_31_136': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_03_197': 'Tufted Titmouse', // testing
    'bird_Recording_2_Recording_2_Segment_04_181': 'Tufted Titmouse', // testing
    'bird_Recording_2_Recording_2_Segment_04_224': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_10_60': 'Ovenbird', // testing
    'bird_Recording_2_Recording_2_Segment_12_57': 'Black-capped Chickadee', // testing
    'bird_Recording_4_Recording_4_Segment_03_114': 'Black-capped Chickadee', // testing
    'bird_Recording_4_Recording_4_Segment_12_8': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_15_133': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_16_197': 'Ovenbird', // testing
    'bird_Recording_4_Recording_4_Segment_16_327': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_24_36': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_23_10': 'Eastern Towhee', // training
    'bird_Recording_1_Recording_1_Segment_24_4': 'Eastern Towhee', // training
    'bird_Recording_2_Recording_2_Segment_04_25': 'Ovenbird', // training
    'bird_Recording_4_Recording_4_Segment_09_140': 'Wood Thrush', // training
    'bird_Recording_4_Recording_4_Segment_22_263': 'Black-capped Chickadee', // training
  },
  'data_v4': {
    // ── lung ──
    'fraiwan_287': 'Stridor', // testing
    'fraiwan_33': 'Stridor', // testing
    'fraiwan_56': 'Crackle', // testing
    'hflung_steth_20190102_10_27_06_4': 'Stridor', // testing
    'hflung_trunc_2019-05-07-16-03-02-L2_10_1': 'Crackle', // testing
    'hflung_trunc_2019-05-28-14-07-13-L5_5_12': 'Rhonchi', // testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_2': 'Normal', // testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_3': 'Crackle', // testing
    'hflung_trunc_2019-07-16-10-41-27-L4_10_5': 'Stridor', // testing
    'hflung_trunc_2019-07-16-11-46-52-L2_7_3': 'Normal', // testing
    'hflung_trunc_2019-08-08-09-36-47-L6_4_11': 'Normal', // testing
    'icbhi_115_1b1_Ar_sc_Meditron_5': 'Crackle', // testing
    'icbhi_118_1b1_Pr_sc_Litt3200_1': 'Crackle', // testing
    'icbhi_156_5b3_Ll_mc_AKGC417L_6': 'Stridor', // testing
    'sprsound_41091768_7.7_0_p1_853_2': 'Rhonchi', // testing
    'sprsound_41132911_3.0_0_p2_6066_4': 'Normal', // testing
    'sprsound_41184079_6.2_0_p3_5761_0': 'Rhonchi', // testing
    'sprsound_64007452_4.6_0_p4_3034_2': 'Crackle', // testing
    'sprsound_64783073_1.3_0_p3_3282_4': 'Normal', // testing
    'sprsound_65043263_2.0_0_p3_319_4': 'Rhonchi', // testing
    'fraiwan_140': 'Rhonchi', // training
    'hflung_trunc_2019-07-16-11-46-52-L5_11_18': 'Stridor', // training
    'hflung_trunc_2019-07-17-10-38-33-L2_5_0': 'Rhonchi', // training
    'hflung_trunc_2019-07-17-11-06-06-L2_9_15': 'Crackle', // training
    'icbhi_116_1b2_Pl_sc_Meditron_3': 'Rhonchi', // training
    // ── bird ──
    'bird_Recording_1_Recording_1_Segment_08_187': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_08_67': 'Ovenbird', // testing
    'bird_Recording_1_Recording_1_Segment_09_33': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_14_178': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_15_40': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_22_56': 'Ovenbird', // testing
    'bird_Recording_1_Recording_1_Segment_23_179': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_23_81': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_32_20': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_36_30': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_03_143': 'Black-capped Chickadee', // testing
    'bird_Recording_2_Recording_2_Segment_03_96': 'Tufted Titmouse', // testing
    'bird_Recording_2_Recording_2_Segment_04_224': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_07_236': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_07_276': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_08_233': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_04_196': 'Wood Thrush', // testing
    'bird_Recording_4_Recording_4_Segment_04_232': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_09_31': 'Black-capped Chickadee', // testing
    'bird_Recording_4_Recording_4_Segment_16_33': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_24_4': 'Eastern Towhee', // training
    'bird_Recording_1_Recording_1_Segment_36_52': 'Eastern Towhee', // training
    'bird_Recording_2_Recording_2_Segment_04_25': 'Ovenbird', // training
    'bird_Recording_2_Recording_2_Segment_07_327': 'Black-capped Chickadee', // training
    'bird_Recording_4_Recording_4_Segment_12_28': 'Black-capped Chickadee', // training
  },
  'data_v5': {
    // ── lung ──
    'fraiwan_287': 'Stridor', // testing
    'fraiwan_33': 'Stridor', // testing
    'fraiwan_56': 'Crackle', // testing
    'hflung_steth_20190102_10_27_06_4': 'Stridor', // testing
    'hflung_trunc_2019-05-07-16-03-02-L2_10_1': 'Crackle', // testing
    'hflung_trunc_2019-05-28-14-07-13-L5_5_12': 'Rhonchi', // testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_2': 'Normal', // testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_3': 'Crackle', // testing
    'hflung_trunc_2019-07-16-10-41-27-L4_10_5': 'Stridor', // testing
    'hflung_trunc_2019-07-16-11-46-52-L2_7_3': 'Normal', // testing
    'hflung_trunc_2019-08-08-09-36-47-L6_4_11': 'Normal', // testing
    'icbhi_115_1b1_Ar_sc_Meditron_5': 'Crackle', // testing
    'icbhi_118_1b1_Pr_sc_Litt3200_1': 'Crackle', // testing
    'icbhi_156_5b3_Ll_mc_AKGC417L_6': 'Stridor', // testing
    'sprsound_41091768_7.7_0_p1_853_2': 'Rhonchi', // testing
    'sprsound_41132911_3.0_0_p2_6066_4': 'Normal', // testing
    'sprsound_41184079_6.2_0_p3_5761_0': 'Rhonchi', // testing
    'sprsound_64007452_4.6_0_p4_3034_2': 'Crackle', // testing
    'sprsound_64783073_1.3_0_p3_3282_4': 'Normal', // testing
    'sprsound_65043263_2.0_0_p3_319_4': 'Rhonchi', // testing
    'fraiwan_140': 'Rhonchi', // training
    'hflung_trunc_2019-07-16-11-46-52-L5_11_18': 'Stridor', // training
    'hflung_trunc_2019-07-17-10-38-33-L2_5_0': 'Rhonchi', // training
    'hflung_trunc_2019-07-17-11-06-06-L2_9_15': 'Crackle', // training
    'icbhi_116_1b2_Pl_sc_Meditron_3': 'Rhonchi', // training
    // ── bird ──
    'bird_Recording_1_Recording_1_Segment_08_187': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_08_67': 'Ovenbird', // testing
    'bird_Recording_1_Recording_1_Segment_09_33': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_14_178': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_15_40': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_22_56': 'Ovenbird', // testing
    'bird_Recording_1_Recording_1_Segment_23_179': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_23_81': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_32_20': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_36_30': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_03_143': 'Black-capped Chickadee', // testing
    'bird_Recording_2_Recording_2_Segment_03_96': 'Tufted Titmouse', // testing
    'bird_Recording_2_Recording_2_Segment_04_224': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_07_236': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_07_276': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_08_233': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_04_196': 'Wood Thrush', // testing
    'bird_Recording_4_Recording_4_Segment_04_232': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_09_31': 'Black-capped Chickadee', // testing
    'bird_Recording_4_Recording_4_Segment_16_33': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_24_4': 'Eastern Towhee', // training
    'bird_Recording_1_Recording_1_Segment_36_52': 'Eastern Towhee', // training
    'bird_Recording_2_Recording_2_Segment_04_25': 'Ovenbird', // training
    'bird_Recording_2_Recording_2_Segment_07_327': 'Black-capped Chickadee', // training
    'bird_Recording_4_Recording_4_Segment_12_28': 'Black-capped Chickadee', // training
  },
  'data_v6': {
    // ── lung ──
    'hflung_steth_20190102_10_27_06_2': 'Normal', // post-test
    'hflung_trunc_2019-05-07-16-03-02-L2_10_5': 'Normal', // post-test
    'hflung_trunc_2019-06-23-11-02-58-L8_3_0': 'Stridor', // post-test
    'sprsound_41042359_9.0_1_p2_21901_1': 'Stridor', // post-test
    'sprsound_41223618_1.0_0_p1_3607_1': 'Crackle', // post-test
    'sprsound_64739121_2.0_0_p3_7742_4': 'Crackle', // post-test
    'fraiwan_33': 'Stridor', // post-test, testing-formative
    'fraiwan_56': 'Crackle', // post-test, testing-formative
    'hflung_trunc_2019-07-16-11-46-52-L2_7_3': 'Normal', // post-test, testing-formative
    'sprsound_41091768_7.7_0_p1_853_2': 'Rhonchi', // post-test, testing-formative
    'hflung_trunc_2019-05-28-14-44-45-L6_0_3': 'Crackle', // testing-formative
    'fraiwan_287': 'Stridor', // testing-formative, testing
    'hflung_steth_20190102_10_27_06_4': 'Stridor', // testing-formative, testing
    'hflung_trunc_2019-05-07-16-03-02-L2_10_1': 'Normal', // testing-formative, testing
    'hflung_trunc_2019-05-28-14-07-13-L5_5_12': 'Rhonchi', // testing-formative, testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_2': 'Normal', // testing-formative, testing
    'hflung_trunc_2019-07-16-10-41-27-L4_10_5': 'Wheeze', // testing-formative, testing
    'hflung_trunc_2019-08-08-09-36-47-L6_4_11': 'Normal', // testing-formative, testing
    'icbhi_115_1b1_Ar_sc_Meditron_5': 'Crackle', // testing-formative, testing
    'icbhi_118_1b1_Pr_sc_Litt3200_1': 'Crackle', // testing-formative, testing
    'icbhi_156_5b3_Ll_mc_AKGC417L_6': 'Wheeze', // testing-formative, testing
    'sprsound_41132911_3.0_0_p2_6066_4': 'Normal', // testing-formative, testing
    'sprsound_41184079_6.2_0_p3_5761_0': 'Rhonchi', // testing-formative, testing
    'sprsound_64007452_4.6_0_p4_3034_2': 'Crackle', // testing-formative, testing
    'sprsound_64783073_1.3_0_p3_3282_4': 'Normal', // testing-formative, testing
    'sprsound_65043263_2.0_0_p3_319_4': 'Rhonchi', // testing-formative, testing
    'fraiwan_140': 'Rhonchi', // training-formative, training
    'hflung_trunc_2019-05-28-14-44-45-L5_5_12': 'Crackle', // training-formative, training
    'hflung_trunc_2019-07-16-11-46-52-L5_11_18': 'Wheeze', // training-formative, training
    'hflung_trunc_2019-07-17-11-06-06-L2_9_15': 'Normal', // training-formative, training
    'icbhi_116_1b2_Pl_sc_Meditron_3': 'Rhonchi', // training-formative, training
    // ── bird ──
    'bird_Recording_1_Recording_1_Segment_09_59': 'Black-capped Chickadee', // post-test
    'bird_Recording_1_Recording_1_Segment_36_12': 'Ovenbird', // post-test
    'bird_Recording_1_Recording_1_Segment_36_55': 'Ovenbird', // post-test
    'bird_Recording_2_Recording_2_Segment_04_192': 'Tufted Titmouse', // post-test
    'bird_Recording_1_Recording_1_Segment_08_187': 'Wood Thrush', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_09_33': 'Black-capped Chickadee', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_32_20': 'Black-capped Chickadee', // post-test, testing-formative
    'bird_Recording_2_Recording_2_Segment_03_96': 'Tufted Titmouse', // post-test, testing-formative
    'bird_Recording_2_Recording_2_Segment_07_276': 'Ovenbird', // post-test, testing-formative
    'bird_Recording_4_Recording_4_Segment_04_196': 'Wood Thrush', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_05_62': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_10_103': 'Ovenbird', // testing
    'bird_Recording_2_Recording_2_Segment_03_143': 'Black-capped Chickadee', // testing-formative
    'bird_Recording_1_Recording_1_Segment_08_67': 'Ovenbird', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_14_178': 'Black-capped Chickadee', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_15_40': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_22_56': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_23_179': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_23_81': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_36_30': 'Eastern Towhee', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_04_224': 'Ovenbird', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_07_236': 'Ovenbird', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_08_233': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_04_232': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_09_31': 'Black-capped Chickadee', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_16_33': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_24_4': 'Eastern Towhee', // training-formative, training
    'bird_Recording_2_Recording_2_Segment_04_25': 'Ovenbird', // training-formative, training
    'bird_Recording_2_Recording_2_Segment_05_121': 'Tufted Titmouse', // training-formative, training
    'bird_Recording_4_Recording_4_Segment_02_125': 'Wood Thrush', // training-formative, training
    'bird_Recording_4_Recording_4_Segment_26_76': 'Ovenbird', // training-formative, training
  },
  'data_v6.1': {
    // ── lung ──
    'hflung_steth_20190102_10_27_06_2': 'Normal', // post-test
    'hflung_trunc_2019-05-07-16-03-02-L2_10_5': 'Normal', // post-test
    'hflung_trunc_2019-06-23-11-02-58-L8_3_0': 'Stridor', // post-test
    'sprsound_41042359_9.0_1_p2_21901_1': 'Stridor', // post-test
    'sprsound_41223618_1.0_0_p1_3607_1': 'Crackle', // post-test
    'sprsound_64739121_2.0_0_p3_7742_4': 'Crackle', // post-test
    'fraiwan_33': 'Stridor', // post-test, testing-formative
    'fraiwan_56': 'Crackle', // post-test, testing-formative
    'hflung_trunc_2019-07-16-11-46-52-L2_7_3': 'Normal', // post-test, testing-formative
    'sprsound_41091768_7.7_0_p1_853_2': 'Rhonchi', // post-test, testing-formative
    'hflung_trunc_2019-05-28-14-44-45-L6_0_3': 'Crackle', // testing-formative
    'fraiwan_287': 'Stridor', // testing-formative, testing
    'hflung_steth_20190102_10_27_06_4': 'Stridor', // testing-formative, testing
    'hflung_trunc_2019-05-07-16-03-02-L2_10_1': 'Normal', // testing-formative, testing
    'hflung_trunc_2019-05-28-14-07-13-L5_5_12': 'Rhonchi', // testing-formative, testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_2': 'Normal', // testing-formative, testing
    'hflung_trunc_2019-07-16-10-41-27-L4_10_5': 'Wheeze', // testing-formative, testing
    'hflung_trunc_2019-08-08-09-36-47-L6_4_11': 'Normal', // testing-formative, testing
    'icbhi_115_1b1_Ar_sc_Meditron_5': 'Crackle', // testing-formative, testing
    'icbhi_118_1b1_Pr_sc_Litt3200_1': 'Crackle', // testing-formative, testing
    'icbhi_156_5b3_Ll_mc_AKGC417L_6': 'Wheeze', // testing-formative, testing
    'sprsound_41132911_3.0_0_p2_6066_4': 'Normal', // testing-formative, testing
    'sprsound_41184079_6.2_0_p3_5761_0': 'Rhonchi', // testing-formative, testing
    'sprsound_64007452_4.6_0_p4_3034_2': 'Crackle', // testing-formative, testing
    'sprsound_64783073_1.3_0_p3_3282_4': 'Normal', // testing-formative, testing
    'sprsound_65043263_2.0_0_p3_319_4': 'Rhonchi', // testing-formative, testing
    'fraiwan_140': 'Rhonchi', // training-formative, training
    'hflung_trunc_2019-05-28-14-44-45-L5_5_12': 'Crackle', // training-formative, training
    'hflung_trunc_2019-07-16-11-46-52-L5_11_18': 'Wheeze', // training-formative, training
    'hflung_trunc_2019-07-17-11-06-06-L2_9_15': 'Normal', // training-formative, training
    'icbhi_116_1b2_Pl_sc_Meditron_3': 'Rhonchi', // training-formative, training
    // ── bird ──
    'bird_Recording_1_Recording_1_Segment_09_59': 'Black-capped Chickadee', // post-test
    'bird_Recording_1_Recording_1_Segment_36_12': 'Ovenbird', // post-test
    'bird_Recording_1_Recording_1_Segment_36_55': 'Ovenbird', // post-test
    'bird_Recording_2_Recording_2_Segment_04_192': 'Tufted Titmouse', // post-test
    'bird_Recording_1_Recording_1_Segment_08_187': 'Wood Thrush', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_09_33': 'Black-capped Chickadee', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_32_20': 'Black-capped Chickadee', // post-test, testing-formative
    'bird_Recording_2_Recording_2_Segment_03_96': 'Tufted Titmouse', // post-test, testing-formative
    'bird_Recording_2_Recording_2_Segment_07_276': 'Ovenbird', // post-test, testing-formative
    'bird_Recording_4_Recording_4_Segment_04_196': 'Wood Thrush', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_05_62': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_10_103': 'Ovenbird', // testing
    'bird_Recording_2_Recording_2_Segment_03_143': 'Black-capped Chickadee', // testing-formative
    'bird_Recording_1_Recording_1_Segment_08_67': 'Ovenbird', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_14_178': 'Black-capped Chickadee', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_15_40': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_22_56': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_23_179': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_23_81': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_36_30': 'Eastern Towhee', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_04_224': 'Ovenbird', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_07_236': 'Ovenbird', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_08_233': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_04_232': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_09_31': 'Black-capped Chickadee', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_16_33': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_24_4': 'Eastern Towhee', // training-formative, training
    'bird_Recording_2_Recording_2_Segment_04_25': 'Ovenbird', // training-formative, training
    'bird_Recording_2_Recording_2_Segment_05_121': 'Tufted Titmouse', // training-formative, training
    'bird_Recording_4_Recording_4_Segment_02_125': 'Wood Thrush', // training-formative, training
    'bird_Recording_4_Recording_4_Segment_26_76': 'Ovenbird', // training-formative, training
  },
  'data_v7': {
    // ── lung ──
    'fraiwan_56': 'Crackle', // post-test
    'hflung_trunc_2019-05-07-16-03-02-L2_10_5': 'Normal', // post-test
    'hflung_trunc_2019-06-23-11-02-58-L8_3_0': 'Stridor', // post-test
    'sprsound_41223618_1.0_0_p1_3607_1': 'Crackle', // post-test
    'sprsound_64739121_2.0_0_p3_7742_4': 'Crackle', // post-test
    'fraiwan_33': 'Stridor', // post-test, testing-formative
    'hflung_steth_20190102_10_27_06_2': 'Normal', // post-test, testing-formative
    'hflung_trunc_2019-07-16-11-46-52-L2_7_3': 'Normal', // post-test, testing-formative
    'sprsound_41042359_9.0_1_p2_21901_1': 'Stridor', // post-test, testing-formative
    'sprsound_41091768_7.7_0_p1_853_2': 'Rhonchi', // post-test, testing-formative
    'fraiwan_287': 'Stridor', // testing-formative, testing
    'hflung_steth_20190102_10_27_06_4': 'Stridor', // testing-formative, testing
    'hflung_trunc_2019-05-07-16-03-02-L2_10_1': 'Normal', // testing-formative, testing
    'hflung_trunc_2019-05-28-14-07-13-L5_5_12': 'Rhonchi', // testing-formative, testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_2': 'Normal', // testing-formative, testing
    'hflung_trunc_2019-07-16-10-41-27-L4_10_5': 'Wheeze', // testing-formative, testing
    'hflung_trunc_2019-08-08-09-36-47-L6_4_11': 'Normal', // testing-formative, testing
    'icbhi_115_1b1_Ar_sc_Meditron_5': 'Crackle', // testing-formative, testing
    'icbhi_118_1b1_Pr_sc_Litt3200_1': 'Crackle', // testing-formative, testing
    'icbhi_156_5b3_Ll_mc_AKGC417L_6': 'Wheeze', // testing-formative, testing
    'sprsound_41132911_3.0_0_p2_6066_4': 'Normal', // testing-formative, testing
    'sprsound_41184079_6.2_0_p3_5761_0': 'Rhonchi', // testing-formative, testing
    'sprsound_64007452_4.6_0_p4_3034_2': 'Crackle', // testing-formative, testing
    'sprsound_64783073_1.3_0_p3_3282_4': 'Normal', // testing-formative, testing
    'sprsound_65043263_2.0_0_p3_319_4': 'Rhonchi', // testing-formative, testing
    'sprsound_41161556_1.7_0_p4_3098_3': 'Normal', // training
    'hflung_trunc_2019-07-17-11-06-06-L2_9_15': 'Normal', // training-formative
    'fraiwan_140': 'Rhonchi', // training-formative, training
    'hflung_trunc_2019-05-28-14-44-45-L5_5_12': 'Crackle', // training-formative, training
    'hflung_trunc_2019-07-16-11-46-52-L5_11_18': 'Wheeze', // training-formative, training
    'icbhi_116_1b2_Pl_sc_Meditron_3': 'Rhonchi', // training-formative, training
    // ── bird ──
    'bird_Recording_1_Recording_1_Segment_23_169': 'Black-capped Chickadee', // post-test
    'bird_Recording_1_Recording_1_Segment_34_4': 'Black-capped Chickadee', // post-test
    'bird_Recording_2_Recording_2_Segment_01_17': 'Black-capped Chickadee', // post-test
    'bird_Recording_4_Recording_4_Segment_06_92': 'Tufted Titmouse', // post-test
    'bird_Recording_4_Recording_4_Segment_16_38': 'Eastern Towhee', // post-test
    'bird_Recording_1_Recording_1_Segment_12_150': 'Black-capped Chickadee', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_35_84': 'Blue Jay', // post-test, testing-formative
    'bird_Recording_2_Recording_2_Segment_01_97': 'Black-capped Chickadee', // post-test, testing-formative
    'bird_Recording_2_Recording_2_Segment_08_22': 'Eastern Towhee', // post-test, testing-formative
    'bird_Recording_4_Recording_4_Segment_10_39': 'Tufted Titmouse', // post-test, testing-formative
    'bird_Recording_1_Recording_1_Segment_04_38': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_06_19': 'Blue Jay', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_08_75': 'Blue Jay', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_10_80': 'Eastern Towhee', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_19_52': 'Eastern Towhee', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_34_17': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_36_12': 'Blue Jay', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_02_110': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_03_180': 'Blue Jay', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_07_299': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_2_Recording_2_Segment_08_284': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_01_205': 'Eastern Towhee', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_02_200': 'Eastern Towhee', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_02_85': 'Tufted Titmouse', // testing-formative, testing
    'bird_Recording_4_Recording_4_Segment_04_219': 'Wood Thrush', // testing-formative, testing
    'bird_Recording_1_Recording_1_Segment_07_219': 'Black-capped Chickadee', // training-formative, training
    'bird_Recording_1_Recording_1_Segment_33_72': 'Black-capped Chickadee', // training-formative, training
    'bird_Recording_2_Recording_2_Segment_01_60': 'Black-capped Chickadee', // training-formative, training
    'bird_Recording_2_Recording_2_Segment_05_31': 'Blue Jay', // training-formative, training
    'bird_Recording_4_Recording_4_Segment_01_173': 'Wood Thrush', // training-formative, training
  },
  'data_v8_2': {
    // ── lung ──
    'fraiwan_287': 'Stridor', // testing
    'fraiwan_55': 'Stridor', // testing
    'hflung_steth_20190102_10_27_06_2': 'Normal', // testing
    'hflung_steth_20190102_10_27_06_4': 'Stridor', // testing
    'hflung_trunc_2019-05-07-16-03-02-L2_10_1': 'Normal', // testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_2': 'Normal', // testing
    'hflung_trunc_2019-05-28-14-44-45-L6_0_3': 'Crackle', // testing
    'hflung_trunc_2019-07-16-10-41-27-L4_10_5': 'Wheeze', // testing
    'hflung_trunc_2019-07-16-11-46-52-L2_7_3': 'Normal', // testing
    'hflung_trunc_2019-08-08-09-36-47-L6_4_11': 'Normal', // testing
    'icbhi_115_1b1_Ar_sc_Meditron_5': 'Crackle', // testing
    'icbhi_156_5b3_Ll_mc_AKGC417L_6': 'Wheeze', // testing
    'sprsound_41042359_9.0_1_p2_21901_1': 'Stridor', // testing
    'sprsound_41091768_7.7_0_p1_853_2': 'Rhonchi', // testing
    'sprsound_41132911_3.0_0_p2_6066_2': 'Wheeze', // testing
    'sprsound_41184079_6.2_0_p3_5761_0': 'Rhonchi', // testing
    'sprsound_64007452_4.6_0_p4_3034_2': 'Crackle', // testing
    'sprsound_64743918_7.0_0_p1_2518_0': 'Rhonchi', // testing
    'sprsound_65043263_2.0_0_p3_319_4': 'Rhonchi', // testing
    'sprsound_65099422_0.5_0_p2_2760_0': 'Rhonchi', // testing
    // ── bird ──
    'bird_Recording_1_Recording_1_Segment_04_38': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_06_19': 'Blue Jay', // testing
    'bird_Recording_1_Recording_1_Segment_08_75': 'Blue Jay', // testing
    'bird_Recording_1_Recording_1_Segment_10_80': 'Eastern Towhee', // testing
    'bird_Recording_1_Recording_1_Segment_12_150': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_12_175': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_23_169': 'Black-capped Chickadee', // testing
    'bird_Recording_1_Recording_1_Segment_34_17': 'Tufted Titmouse', // testing
    'bird_Recording_1_Recording_1_Segment_36_12': 'Blue Jay', // testing
    'bird_Recording_2_Recording_2_Segment_01_17': 'Black-capped Chickadee', // testing
    'bird_Recording_2_Recording_2_Segment_02_110': 'Tufted Titmouse', // testing
    'bird_Recording_2_Recording_2_Segment_03_180': 'Blue Jay', // testing
    'bird_Recording_2_Recording_2_Segment_07_299': 'Tufted Titmouse', // testing
    'bird_Recording_2_Recording_2_Segment_08_22': 'Eastern Towhee', // testing
    'bird_Recording_2_Recording_2_Segment_08_284': 'Wood Thrush', // testing
    'bird_Recording_2_Recording_2_Segment_10_238': 'Wood Thrush', // testing
    'bird_Recording_4_Recording_4_Segment_01_205': 'Eastern Towhee', // testing
    'bird_Recording_4_Recording_4_Segment_02_200': 'Eastern Towhee', // testing
    'bird_Recording_4_Recording_4_Segment_02_85': 'Tufted Titmouse', // testing
    'bird_Recording_4_Recording_4_Segment_19_142': 'Black-capped Chickadee', // testing
  },
};

/** The pinned counterfactual class for a study sample, or undefined when the
 *  sample is not in the table (dev browsing outside the split CSVs, or a
 *  bundle that ships no split lists). Callers fall back to the hash. */
export function pinnedFoilClass(
  root: string | undefined,
  sampleId: string | undefined
): string | undefined {
  if (!root || !sampleId) return undefined;
  return FOIL_OVERRIDES[root]?.[sampleId];
}
